[package]
name = "magick_rust_6"
version = "0.6.6"
authors = ["Nathan Fiedler <nathanfiedler@fastmail.fm>"]
description = "Selection of Rust bindings for the ImageMagick library."
homepage = "https://github.com/nlfiedler/magick-rust"
repository = "https://github.com/nlfiedler/magick-rust.git"
readme = "README.md"
license = "Apache-2.0"
keywords = ["magickwand", "imagemagick"]
build = "build.rs"

[dependencies]
libc = ">=0.2"

[build-dependencies]
# bindgen 0.26.x results in "already been defined in this module" errors (bug #687)
bindgen = "0.25.5"
pkg-config = "0.3.9"
